//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB
    {
        public string JOB_ID { get; set; }
        public string JOB_TITLE { get; set; }
        public Nullable<decimal> MIN_SALARY { get; set; }
        public Nullable<decimal> MAX_SALARY { get; set; }
    }
}
