//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_grades
    {
        public string grade { get; set; }
        public decimal lowest_sal { get; set; }
        public decimal highest_sal { get; set; }
    }
}
